ekf_filter_node:
  ros__parameters:
    frequency: 100.0
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    two_d_mode: true

    # IMU
    imu0: /imu_madgwick
    imu0_config: [false, false, false,   # x y z
	          false, false, false,         # roll pitch yaw
	          false, false, false,         # vx vy vz 
	          false, false, false,         # vroll vpitch vyaw
	          false, false, false]         # ax ay az
    imu0_remove_gravitational_acceleration: false
    
    # Odometry
    odom0: /odometry/raw
    odom0_config: [false, false, false,    # x y z
                   false, false, false,    # roll pitch yaw
                   true, true, false,      # vx vy vz
                   false, false, true,     # angular velocity
                   false, false, false]    # linear accel

    publish_tf: true