amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_beams: 60
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    subscribers:
      map:
        topic: /map
        qos:
          durability: transient_local
          reliability: reliable
          depth: 1

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/nvidia/ros2-ws/SLAMurai/autonav/rs/maps/kitchen.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    expected_controller_frequency: 10.0
    controller_plugins: ["DWB"]
    DWB:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.21
      min_vel_x: -0.21
      max_vel_y: 0.21
      min_vel_y: -0.21
      max_vel_theta: 1.5
      min_vel_theta: -1.5
      acc_lim_x: 0.2
      acc_lim_y: 0.2
      acc_lim_theta: 0.75
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05
      sim_time: 1.7
      sim_granularity: 0.025
      vx_samples: 20
      vy_samples: 20
      vtheta_samples: 20
      occdist_scale: 0.01
      pdist_scale: 0.6
      gdist_scale: 0.8

bt_navigator:
  ros__parameters:
    use_sim_time: false

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 1.0
    rolling_window: false
    width: 5.0
    height: 5.0
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d/StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d/ObstacleLayer"
      observation_sources: scan
      scan: {sensor_frame: lidar_link, data_type: LaserScan, marking: true, clearing: true}
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      inflation_radius: 0.55

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 2.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d/ObstacleLayer"
      observation_sources: scan
      scan: {sensor_frame: lidar_link, data_type: LaserScan, marking: true, clearing: true}
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      inflation_radius: 0.2