slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_params_file: ""
    mode: "mapping"
    map_file_name: ""
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"
    resolution: 0.05
    transform_publish_period: 0.05
    map_update_interval: 1.0
    use_scan_matching: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    max_laser_range: 4.0
    min_laser_range: 0.05

    distance_variance_penalty: 2.0             # increase cost of deviating from odom in XY
    angle_variance_penalty: 2.0                # increase cost of deviating from odom in yaw
    coarse_search_angle_offset: 0.35           # 20� search window; minimum safe
    correlation_search_space_dimension: 0.20   # safe minimum XY window
    use_response_expansion: false              # prevent expanding search when match is weak

