slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_params_file: ""
    mode: "mapping"
    map_file_name: ""
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"
    resolution: 0.05
    transform_publish_period: 0.02
    map_update_interval: 1.0
    use_scan_matching: false
    minimum_travel_distance: 0.00
    minimum_travel_heading: 0.00
    max_laser_range: 4.0


