ekf_filter_node:
  ros__parameters:
    frequency: 40.0
    # set odom_frame = world_frame, so ekf publishes odom_frame -> base_link_frame
    odom_frame: odom 
    world_frame: odom
    base_link_frame: base_footprint
    two_d_mode: true

    # Currently no fusion, RealSense IMU is too mid. EKF provides smoothing
    imu0: /imu_madgwick
    imu0_config: [false, false, false,      # x y z
                  false, false, false,      # roll pitch yaw
                  false, false, false,      # vx vy vz 
                  false, false, false,      # vroll vpitch vyaw
                  false, false, false]      # ax ay az
    imu0_remove_gravitational_acceleration: true
    
    # Odometry is given by motor ticks because system is open-loop due to using stepper motors 
    odom0: /odometry/raw
    odom0_config: [true, true, true,       # x y z
                   false, false, true,     # roll pitch yaw
                   true, true, true,       # vx vy vz
                   false, false, false,    # angular velocity
                   false, false, false]    # linear accel

    publish_tf: true # Publish world_frame -> base_link_frame